name: dartz_test
description: Provides matchers to help unit-testing your apps when using functional programming types defined in the dartz package.
repository: https://github.com/SuperMuel/dartz_test

version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
